inventory/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('inventory_app.urls')),
    url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT})
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory_app/urls.py
from django.conf.urls import url
from inventory_app import views

urlpatterns = [url(r'^$', views.index, name='index'),
              url(r'^categories/', views.categories, name='categories'),
              url(r'^outlets/', views.outlets, name='outlets'),
              url(r'^item/(?P<id>[0-9]+)/$', views.item, name='item'),
              url(r'^category/(?P<id>[0-9]+)/$', views.category, name='category'),
              url(r'^outlet/(?P<id>[0-9]+)/$', views.outlet, name='outlet'),
              url(r'^search/', views.searchResults, name='search'),
              ]

inventory_app/models.py
from django.db import models

class Item(models.Model):
  name = models.CharField(max_length=100, blank=False)
  last_modified = models.DateTimeField(auto_now=True)
  total = models.IntegerField(default=0)
  image = models.ImageField(upload_to="images", blank=True, null=True)
  description = models.TextField(blank=True)
  category = models.ForeignKey('Category', on_delete=models.CASCADE)
  outlets = models.ManyToManyField('Outlet', through='Count')

  def __str__(self):
    return self.name

class Category(models.Model):
  name = models.CharField(max_length=50, blank=False)

  def __str__(self):
    return self.name

class Outlet(models.Model):
  name = models.CharField(max_length=50, blank=False)

  def __str__(self):
    return self.name

# Add field to many to many relationship - count for each outlet and item
class Count(models.Model):
  outlet = models.ForeignKey(Outlet)
  item = models.ForeignKey(Item)
  amount = models.IntegerField(default=0)

inventory_app/views.py
from django.shortcuts import render, get_object_or_404
from django.template import Context, loader
from django.http import HttpResponse

from inventory_app.models import Item, Category, Outlet, Count
import operator
from functools import reduce
from django.db.models import Q

def index(request):
  items = Item.objects.all()
  t = loader.get_template('index.html')
  c = Context({ 'items': items, })
  return HttpResponse(t.render(c))

def categories(request):
  categories = Category.objects.all().order_by('name')
  t = loader.get_template('categories.html')
  c = Context({ 'categories': categories, })
  return HttpResponse(t.render(c))

def outlets(request):
  outlets = Outlet.objects.all().order_by('name')
  t = loader.get_template('outlets.html')
  c = Context({ 'outlets': outlets, })
  return HttpResponse(t.render(c))

def category(request, id):
  category = get_object_or_404(Category, id=id)
  items = Item.objects.filter(category=id)
  t = loader.get_template('category.html')
  c = Context({ 'category': category, 'items': items })
  return HttpResponse(t.render(c))

def outlet(request, id):
  outlet = get_object_or_404(Outlet, id=id)
  counts = Count.objects.filter(outlet=id)
  items = [c.item for c in counts]
  t = loader.get_template('outlet.html')
  c = Context({ 'outlet': outlet, 'items': items })
  return HttpResponse(t.render(c))

def item(request, id):
  item = get_object_or_404(Item, id=id)
  t = loader.get_template('item.html')
  c = Context({ 'item': item })
  return HttpResponse(t.render(c))

def searchResults(request):
  items = get_queryset(request)
  t = loader.get_template('searchResults.html')
  c = Context({ 'items': items })
  return HttpResponse(t.render(c))

# Adapted from: https://www.calazan.com/adding-basic-search-to-your-django-site/
def get_queryset(req):
  query = req.GET.get('q')
  if query:
    query_list = query.split()
    items = Item.objects.all()
    result = items.filter(
      reduce(operator.and_,
          (Q(name__icontains=q) for q in query_list)) |
      reduce(operator.and_,
          (Q(description__icontains=q) for q in query_list))
      )
  return result

templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width, initial-sale=1.0">
    <meta name="description" content="An inventory app to keep track of different wares and equipment in a stewarding department.">
    <meta name="author" content="">

    <!-- Style -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico">
    {% load staticfiles %}
    <link href="{% static "styles/style.css" %}" rel="stylesheet">
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header pull-left">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" aria-expanded="false" data-target="#nav-collapse-links">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand visible-lg visible-md" href="/">Inventory</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse col-md-7 col-sm-6 col-xs-5" id="nav-collapse-links">
          <ul class="nav navbar-nav">
            <li class="visible-sm visible-xs"><a href="/">Inventory</a></li>
            <li><a href="/categories">Categories</a></li>
            <li><a href="/outlets">Outlets</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
        <div class="col-md-3 col-sm-5 col-xs-6 pull-right" id="search">
          <form class="navbar-form" role="search" action="{% url 'search' %}" method="get" accept-charset="utf-8">
            <div class="form-group input-group">
              <input type="text" class="form-control" name="q" placeholder="Search">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </span>
            </div>
          </form>
        </div>
      </div><!-- /.container -->
    </nav>
    <!-- Search
        Source: https://www.calazan.com/adding-basic-search-to-your-django-site/ -->

    <!-- Body -->
    <div class="container" id="content">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="navbar navbar-bottom">
      <div class="container">
        <div class="row" id="footer-content">
          <div class="col-md-4 col-sm-4 col-xs-4">
            <a class="navbar-brand" href="/">Inventory</a>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-4">
            <ul>
              <li><a href="/">Home</a></li>
              <li><a href="/admin">Admin</a></li>
            </ul>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-4">
            <p>An app to keep track of inventory.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/categories.html
{% extends '_base.html' %}

{% block content %}
<h1>Categories</h1>
<ul class="name-list">
  {% for category in categories %}
  <li><a href="/category/{{ category.id }}">{{ category.name }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

templates/category.html
{% extends '_base.html' %}

{% block content %}
<h1>{{ category.name }}</h1>
<div class="row">
  {% for item in items %}
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <a href="/item/{{ item.id }}"><img src="/images/{{item.image}}" alt="{{item.name}}"></a>
        <div class="caption">
          <a href="/item/{{ item.id }}"><h3>{{ item.name }}</h3></a>
          <ul>
            <li>Total: {{ item.total }}</li>
          </ul>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

templates/index.html
{% extends '_base.html' %}

{% block content %}
<h1>Inventory</h1>
<div class="row">
  {% for item in items %}
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <a href="/item/{{ item.id }}"><img src="/images/{{item.image}}" alt="{{item.name}}"></a>
        <div class="caption">
          <a href="/item/{{ item.id }}"><h3>{{ item.name }}</h3></a>
          <ul>
            <li>Total: {{ item.total }}</li>
          </ul>
        </div>
      </div>
      <div class="clearfix visible-sm-block"></div>
    </div>
  {% endfor %}
</div>

{% endblock %}

templates/item.html
{% extends '_base.html' %}

{% block content %}
<div class="center">
  <h1>{{ item.name }}</h1>
  {% if item.image %}
    <img class="fullsize" src="/images/{{item.image}}" alt="{{item.name}}">
  {% endif %}
  <ul>
  {% for outlet in item.count_set.all %}
    <li>{{ outlet.outlet.name }}: {{ outlet.amount }}</li>
  {% endfor %}
    <li>Total: {{ item.total }}</li>
  </ul>
  <p>Description:</br>{{ item.description }}</p>
  <p><small>Category: {{ item.category }}</br>
    Last Modified: {{ item.last_modified }}</small></p>
</div>


{% endblock %}

templates/outlet.html
{% extends '_base.html' %}

{% block content %}
<h1>{{ outlet.name }}</h1>

<div class="row">
  {% for item in items %}
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <a href="/item/{{ item.id }}"><img src="/images/{{item.image}}" alt="{{item.name}}"></a>
        <div class="caption">
          <a href="/item/{{ item.id }}"><h3>{{ item.name }}</h3></a>
          <ul>
            <li>Total: {{ item.total }}</li>
          </ul>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

templates/outlets.html
{% extends '_base.html' %}

{% block content %}
<h1>Outlets</h1>
<ul class="name-list">
  {% for outlet in outlets %}
  <li><a href="/outlet/{{ outlet.id }}">{{ outlet.name }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

templates/searchResults.html
{% extends '_base.html' %}

{% block content %}
<h1>Results</h1>
{% if items %}
  <div class="row">
    {% for item in items %}
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <a href="/item/{{ item.id }}"><img src="/images/{{item.image}}" alt="{{item.name}}"></a>
          <div class="caption">
            <a href="/item/{{ item.id }}"><h3>{{ item.name }}</h3></a>
            <ul>
              <li>Total: {{ item.total }}</li>
            </ul>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>No items found.</p>
{% endif %}

{% endblock %}